version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442      
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  mytest:
    image: jadyjdjady1990/sel-dok
    depends_on:
      - chrome
    volumes:
      - C:\udemy\docker\test-output:/usr/share/jady1/extent-test-output
      - C:\udemy\docker\test-output1:/usr/share/jady1/test-output